---
title: "Data_Analysis"
output: html_document
date: "2024-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)
```

```{r include=FALSE}
# Load Packages
library(readr)
library(ggplot2)
```

```{r include=FALSE}
# Cleaning The Data
cleaned_data <- read_csv("../../output/IMDb_dt.csv")

cleaned_data <- cleaned_data %>%
  rename(average_rating = 'The average rating') %>%
  rename(Number_of_episodes = 'Number of episodes') %>%
  filter(!is.na(Number_of_episodes), !is.na(average_rating))
```

```{r include=FALSE}
#Summary of Descriptive Statistics on Average Ratings
Descriptive_stats <- cleaned_data %>% 
  summarize(
  mean_average_rating = mean(average_rating, na.rm = TRUE),
  median_rating = median(average_rating, na.rm = TRUE),
  min_rating = min(average_rating, na.rm = TRUE),
  max_rating = max(average_rating, na.rm = TRUE),
  num_episodes = n()
)

print(Descriptive_stats)
```


### Regressing Series Rating on Number of Episode

```{r echo=FALSE}
main_model <- lm(average_rating ~ Number_of_episodes, data = cleaned_data)
summary(main_model)
```

The output shows that...


